[container.image]
repository="wso2"
name="nats-mail-notifier"
tag="0.1.0"

[[container.copy.files]]
sourceFile="./Config.toml"
target="./Config.toml"

[[container.copy.files]]
sourceFile="./resources"
target="./resources"
